import type { AlgorithmConfig } from '../types';

export const arrayConfig: AlgorithmConfig[] = [
  { name: 'Bubble Sort', slug: 'bubble-sort', endpoint: 'bubble-sort', category: 'array', defaultInput: '5,3,8,1,2', description: "Imagine your friend lined up their DVD collection in a shelf, but the titles are all out of order. You start from the left, look at two DVDs sitting next to each other, and if the right one should come before the left one, you swap them. You keep walking the shelf doing this swap after swap, pass after pass, until no more swaps are needed — the shelf is sorted. The heaviest out-of-place DVDs slowly \"bubble up\" to their correct spot, which is how it got its name." },
  { name: 'Quick Sort', slug: 'quick-sort', endpoint: 'quick-sort', category: 'array', defaultInput: '5,3,8,1,2,7,4', description: "Imagine you're organizing a pile of receipts on your desk. You grab one receipt at random — that's your pivot. You then go through the rest of the pile putting everything cheaper than the pivot on the left and everything more expensive on the right. Now you have two smaller piles. You repeat the same process on each pile, picking a new pivot each time, until every pile is just one receipt. The Lomuto scheme always picks the last receipt in the current pile as the pivot, then walks through from left to right moving cheaper ones to the front as it goes." },
  { name: 'Merge Sort', slug: 'merge-sort', endpoint: 'merge-sort', category: 'array', defaultInput: '5,3,8,1,2,7,4', description: "Imagine you and a friend are sorting a huge pile of numbered cards. You split the pile in half and each take one. You both keep splitting your halves again and again until everyone is holding just one card — one card is always sorted. Now you start merging back: you and your friend hold your piles face up and compare the top cards one by one, always placing the smaller one into the final sorted pile first. You keep merging piles this way until all the cards are back in one fully sorted stack." },
  { name: 'Binary Search', slug: 'binary-search', endpoint: 'binary-search', category: 'array', needsTarget: true, targetLabel: 'Search target', defaultInput: '1,3,5,7,9,11,13', defaultTarget: 7, description: "Imagine you're looking for a friend's number in an old phone book. You wouldn't start from page 1 — you'd flip to the middle. If your friend's name comes before the middle page, you tear the book in half and only keep the left half. If it comes after, you keep the right half. You keep flipping to the middle of whatever is left, throwing away the half that can't contain the name, until you find it. Binary Search does exactly this — but with a sorted list of numbers." },
  { name: 'Insertion Sort', slug: 'insertion-sort', endpoint: 'insertion-sort', category: 'array', defaultInput: '5,3,8,1,2', description: "Imagine you're being dealt playing cards one at a time. Each time you receive a new card, you slide it into the correct position among the cards already in your hand — shifting the others to make room. You're not sorting your whole hand at once, you're just finding where the new card belongs and inserting it. By the time all cards are dealt, your hand is already fully sorted." },
  { name: 'Selection Sort', slug: 'selection-sort', endpoint: 'selection-sort', category: 'array', defaultInput: '5,3,8,1,2', description: "Imagine you have a row of numbered boxes all mixed up and you want to sort them from smallest to biggest. You scan the entire row to find the smallest box, then drag it to the very beginning. Now you ignore that first box and scan the rest again for the next smallest, dragging it to position two. You keep doing this — each time scanning what's left and pulling the smallest to the front — until the whole row is sorted." },
  { name: 'Two Pointers', slug: 'two-pointers', endpoint: 'two-pointers', category: 'array', needsTarget: true, targetLabel: 'Target sum', defaultInput: '1,2,3,4,5,6,7,8', defaultTarget: 9, description: "Imagine a sorted row of price tags and you're trying to find two items that together cost exactly $9. Instead of checking every possible pair, you place one finger on the cheapest item on the far left and another on the most expensive on the far right. If the two prices add up to too much, move the right finger one step left. If they add up to too little, move the left finger one step right. You keep closing in from both ends until you find the pair that adds up to exactly $9 — or run out of options." },
  { name: 'Sliding Window', slug: 'sliding-window', endpoint: 'sliding-window', category: 'array', needsWindowSize: true, defaultInput: '2,1,5,1,3,2', defaultWindowSize: 3, description: "Imagine you're looking out of a train window that shows exactly 3 houses at a time as the train moves. You want to find the stretch of 3 houses with the highest total value. As the train moves one house forward, the window drops the house at the back and picks up a new one at the front. You keep track of the total value in your current window at all times, updating it as you slide, until you've seen every possible group of 3." },
  { name: "Kadane's Algorithm", slug: 'kadane', endpoint: 'kadane', category: 'array', defaultInput: '-2,1,-3,4,-1,2,1,-5,4', description: "Imagine you're walking a trail and each step either gains or loses you altitude. You want to find the stretch of the trail where you gained the most altitude overall. As you walk, you keep a running total of your current gain. The moment your running total drops below zero, you know this stretch is dragging you down — so you reset and start fresh from the next step. You always remember the highest total you've ever seen, and that's your answer at the end." },
];

export const stringConfig: AlgorithmConfig[] = [
  { name: 'KMP', slug: 'kmp', endpoint: 'kmp', category: 'string', inputType: 'text', inputLabel: 'Text', defaultInput: 'ABABDABACDABABCABAB', needsPattern: true, patternLabel: 'Pattern', defaultPattern: 'ABABCABAB', description: 'Imagine you\'re searching for the word "ABABCABAB" hidden inside a long sentence, reading left to right. Most search methods would back up and start over every time they hit a mismatch. KMP never backs up. Instead, before searching, it studies the pattern itself and figures out: if a mismatch happens mid-pattern, how much of what I already matched can I reuse? For example if you matched "ABAB" before hitting a mismatch, KMP knows "AB" at the end of what you matched also appears at the start of the pattern — so it jumps back just enough to reuse that overlap, instead of starting from scratch.' },
  { name: 'Boyer-Moore', slug: 'boyer-moore', endpoint: 'boyer-moore', category: 'string', inputType: 'text', inputLabel: 'Text', defaultInput: 'HERE IS A SIMPLE EXAMPLE', needsPattern: true, patternLabel: 'Pattern', defaultPattern: 'EXAMPLE', description: 'Imagine you\'re scanning a page looking for the word "EXAMPLE". Instead of reading left to right like most people, Boyer-Moore holds the pattern up against the text and reads it backwards — from right to left. The moment it spots a mismatch, it checks: does this mismatched character even appear anywhere in the pattern? If not, the entire pattern can be skipped past that character in one jump. This is what makes it fast — it skips large chunks of text instead of checking every single character.' },
  { name: 'Rabin-Karp', slug: 'rabin-karp', endpoint: 'rabin-karp', category: 'string', inputType: 'text', inputLabel: 'Text', defaultInput: 'GEEKS FOR GEEKS', needsPattern: true, patternLabel: 'Pattern', defaultPattern: 'GEEK', description: 'Imagine you\'re looking for the word "GEEK" in a long text. Instead of comparing letters one by one each time, Rabin-Karp converts "GEEK" into a number — called a hash. It then slides a same-sized window across the text and converts each window into a number too. If the numbers don\'t match, it moves on instantly without comparing any letters. If the numbers do match, only then does it actually check the letters to confirm. The clever part is that each new window\'s number is calculated by slightly adjusting the previous one, making it very fast.' },
  { name: 'LPS (Manacher)', slug: 'longest-palindrome', endpoint: 'longest-palindrome', category: 'string', inputType: 'text', inputLabel: 'Text', defaultInput: 'babad', description: 'Imagine a word that reads the same forwards and backwards — like "racecar". That\'s a palindrome. Now imagine you want to find the longest such stretch hiding inside a bigger string like "babad". Checking every possible stretch one by one would take forever. Manacher\'s algorithm is smarter — it keeps track of the biggest palindrome it has found so far and uses it as a mirror. Any new stretch that falls inside that mirror has a twin on the other side whose length is already known, so it can be copied instantly instead of rechecked. Only when a stretch reaches or goes beyond the mirror\'s edge does it need to explore new territory.' },
  { name: 'Anagram Detection', slug: 'anagram-detection', endpoint: 'anagram-detection', category: 'string', inputType: 'text', inputLabel: 'Text', defaultInput: 'cbaebabacd', needsPattern: true, patternLabel: 'Pattern', defaultPattern: 'abc', description: 'Imagine you\'re looking for all hidden rearrangements of the word "abc" inside the text "cbaebabacd". An anagram is just a reshuffling of the same letters — "bca", "cab", and "abc" are all anagrams of each other. Anagram Detection slides a window the same size as the pattern across the text, and at each position checks whether the window contains exactly the same letters in any order. Instead of rearranging and comparing every time, it keeps a running count of letters in the current window and updates it with each step — dropping the leftmost letter and picking up the new right one.' },
  { name: 'String Reversal', slug: 'reversal', endpoint: 'reversal', category: 'string', inputType: 'text', inputLabel: 'Text', defaultInput: 'hello', description: 'Imagine a row of lettered tiles spelling "hello". You place one finger on the first tile and another on the last. You swap them, then move both fingers one step inward and swap again. You keep swapping and closing in until your two fingers meet in the middle — at which point the whole word is reversed. That\'s it. No extra tiles needed, everything happens in place.' },
  { name: 'Run-Length Encoding', slug: 'run-length-encoding', endpoint: 'run-length-encoding', category: 'string', inputType: 'text', inputLabel: 'Text', defaultInput: 'aaabbccdddd', description: 'Imagine you\'re sending a text message describing a wall that goes "aaabbccdddd". Instead of typing every letter out, you write "3a2b2c4d" — meaning three a\'s, two b\'s, two c\'s, four d\'s. That\'s Run-Length Encoding. It scans the string from left to right, counts how many times each character repeats in a row, and writes the count followed by the character. It\'s one of the simplest forms of compression and works best when the same character repeats many times in a row.' },
  { name: 'Levenshtein Distance', slug: 'levenshtein', endpoint: 'levenshtein', category: 'string', inputType: 'text', inputLabel: 'Text 1', defaultInput: 'kitten', needsPattern: true, patternLabel: 'Text 2', defaultPattern: 'sitting', description: 'Imagine you mistyped "kitten" and meant to write "sitting". How many fixes does it take to get from one to the other? You can insert a letter, delete a letter, or swap a letter for a different one — each counts as one edit. Levenshtein Distance finds the minimum number of such edits needed. It does this by building a grid where each cell answers: what\'s the cheapest way to match the first few letters of one word to the first few letters of the other? It fills the grid step by step, each cell borrowing the best answer from its neighbors, until the bottom-right corner reveals the final answer.' },
];

export const treeConfig: AlgorithmConfig[] = [
  { name: 'Inorder Traversal', slug: 'inorder', endpoint: 'inorder', category: 'tree', inputLabel: 'BST values', defaultInput: '5,3,7,1,4,6,8', description: 'Imagine a family tree where every person on the left side has a smaller number than their parent, and everyone on the right has a larger one. Inorder Traversal visits the tree by always going as far left as possible first, then reading the current person, then moving right. If you follow this rule all the way through, you end up reading every number in the tree from smallest to biggest — like magic, it comes out perfectly sorted.' },
  { name: 'Preorder Traversal', slug: 'preorder', endpoint: 'preorder', category: 'tree', inputLabel: 'BST values', defaultInput: '5,3,7,1,4,6,8', description: 'Using the same family tree, Preorder Traversal visits the parent first, then goes left, then goes right. Think of it as a leader who always announces themselves before introducing their left side and then their right side. This order is useful when you want to copy or recreate the tree exactly, because you always know the parent before its children.' },
  { name: 'Postorder Traversal', slug: 'postorder', endpoint: 'postorder', category: 'tree', inputLabel: 'BST values', defaultInput: '5,3,7,1,4,6,8', description: 'Still in the same family tree, Postorder Traversal visits the left side first, then the right side, and only then reads the parent — children before parents, always. Think of it as cleaning up a tree of folders on your computer: you have to empty every subfolder before you can delete the parent folder. The root is always the very last thing visited.' },
  { name: 'Level Order (BFS)', slug: 'level-order', endpoint: 'level-order', category: 'tree', inputLabel: 'BST values', defaultInput: '5,3,7,1,4,6,8', description: 'Imagine the tree as a company org chart. Level Order visits every person floor by floor — the CEO first, then all managers on the second floor, then all team leads on the third, and so on. It uses a queue — a waiting line — to keep track of who\'s next. Each time it visits someone, it adds their left and right children to the back of the line, ensuring everyone on the current floor is visited before anyone on the next floor.' },
  { name: 'BST Insert / Search', slug: 'bst-insert-search', endpoint: 'bst-insert-search', category: 'tree', inputLabel: 'BST values', defaultInput: '5,3,7,1,4,6,8', needsTarget: true, targetLabel: 'Search for', defaultTarget: 4, description: 'Imagine a filing cabinet where every folder is numbered. Smaller numbers go in the left drawer, bigger numbers go in the right drawer — and this rule applies inside every drawer too. To insert a new number, you start at the top and keep going left if your number is smaller or right if it\'s bigger, until you find an empty spot. Searching works the same way — at every step you either find your number, go left, or go right. You never have to check every folder, just follow the rule.' },
  { name: 'Tree Height', slug: 'height', endpoint: 'height', category: 'tree', inputLabel: 'BST values', defaultInput: '5,3,7,1,4,6,8', description: 'Imagine you\'re standing at the top of a tree and want to know how many floors it has. You send a scout down every branch, all the way to the last leaf. Each scout counts how many steps they took to reach the bottom and reports back. You take the longest report — that\'s the height of the tree. The algorithm does this by asking each node: how tall is your left side? How tall is your right side? Take the bigger one and add one for the current floor.' },
  { name: 'Lowest Common Ancestor', slug: 'lca', endpoint: 'lca', category: 'tree', inputLabel: 'BST values', defaultInput: '5,3,7,1,4,6,8', needsTarget: true, targetLabel: 'Node A', defaultTarget: 1, needsPattern: true, patternLabel: 'Node B', defaultPattern: '4', description: 'Imagine two cousins in a family tree and you want to find the closest relative they share. Starting from the top of the tree, you ask at each person: are both cousins in my left side? Both in my right? Or do they split here — one left, one right? The moment they split, or the moment you land on one of them directly, that\'s the lowest common ancestor — the closest shared family member between the two.' },
  { name: 'Invert Binary Tree', slug: 'invert', endpoint: 'invert', category: 'tree', inputLabel: 'BST values', defaultInput: '5,3,7,1,4,6,8', description: 'Imagine looking at a tree in a mirror. Every left branch becomes a right branch, and every right branch becomes a left branch — all the way down to the last leaf. Invert Binary Tree does exactly this: starting at the top, it swaps the left and right children of every single node, then goes deeper and does the same for every node below, until the entire tree is flipped like a mirror image of itself.' },
  { name: 'Validate BST', slug: 'validate-bst', endpoint: 'validate-bst', category: 'tree', inputLabel: 'BST values', defaultInput: '5,3,7,1,4,6,8', description: 'Remember how Inorder Traversal reads a valid BST in perfectly sorted order? Validate BST uses that exact trick. It walks the tree in inorder — left, root, right — and checks that every number it reads is larger than the one before it. If the sequence ever goes backwards, the tree is not a valid BST. If it stays in order all the way to the end, the tree passes the test.' },
  { name: 'Diameter of Binary Tree', slug: 'diameter', endpoint: 'diameter', category: 'tree', inputLabel: 'BST values', defaultInput: '5,3,7,1,4,6,8', description: 'Imagine stretching a piece of string between two leaves in a tree, pulling it tight through whatever branches connect them. The diameter is the longest such string you can find — the longest path between any two nodes, anywhere in the tree. For every node, the algorithm asks: what\'s the longest path that passes through me, combining my deepest left branch and my deepest right branch? It keeps track of the longest answer seen across every node, and that\'s the diameter.' },
  { name: 'Huffman Encoding', slug: 'huffman', endpoint: 'huffman', category: 'tree', inputType: 'text', inputLabel: 'Text', defaultInput: 'huffman encoding example', description: 'Imagine you\'re sending a long message and want to shrink it as much as possible. Letters that appear often should take up less space, and rare letters can afford to take up more. Huffman Encoding counts how often each letter appears, then builds a tree where the most frequent letters end up closest to the top and the rarest sink to the bottom. Each left branch means "0" and each right branch means "1", so every letter gets its own unique binary code based on its path from the top. The result is a compressed version of the text where common letters are represented by just a few bits.' },
];

export const graphConfig: AlgorithmConfig[] = [
  { name: 'BFS', slug: 'bfs', endpoint: 'bfs', category: 'graph', inputType: 'graph', inputLabel: 'Graph (nodes;from,to;...)', defaultInput: '6;0,1;0,2;1,3;2,3;3,4;4,5', needsTarget: true, targetLabel: 'Start node', defaultTarget: 0, description: 'Imagine you\'re standing in the middle of a city and want to explore every street, starting from your current corner. BFS explores the city floor by floor — first every street directly connected to you, then every street connected to those, then the next ring out, and so on. It uses a waiting line: every time you visit a corner, you add all its unvisited neighbors to the back of the line. You always visit the person at the front of the line next, which guarantees you explore everything close to you before venturing further away.' },
  { name: 'DFS', slug: 'dfs', endpoint: 'dfs', category: 'graph', inputType: 'graph', inputLabel: 'Graph (nodes;from,to;...)', defaultInput: '6;0,1;0,2;1,3;2,3;3,4;4,5', needsTarget: true, targetLabel: 'Start node', defaultTarget: 0, description: 'Using the same city, DFS explores very differently. Instead of fanning out in all directions, it picks one street and follows it as far as it possibly can — turning down every new road it finds — until it hits a dead end. Only then does it backtrack to the last junction and try a different road. Think of it as exploring a maze by always hugging the left wall: you go deep into one path completely before trying another.' },
  { name: "Dijkstra's Shortest Path", slug: 'dijkstra', endpoint: 'dijkstra', category: 'graph', inputType: 'graph', inputLabel: 'Graph (nodes;from,to,weight;...)', defaultInput: '5;0,1,4;0,2,1;1,3,1;2,1,2;2,3,5;3,4,3', needsTarget: true, targetLabel: 'Start node', defaultTarget: 0, description: 'Imagine you\'re a GPS trying to find the fastest route from your home to every other location in a city. Each road has a travel time. Dijkstra\'s algorithm starts at your home and always visits the closest unvisited location next — the one with the smallest total travel time from home. When it visits a location, it checks whether going through it offers a faster route to any of its neighbors, and updates the estimate if so. It keeps doing this, always picking the cheapest unvisited stop, until it has found the shortest path to everywhere.' },
  { name: 'Bellman-Ford', slug: 'bellman-ford', endpoint: 'bellman-ford', category: 'graph', inputType: 'graph', inputLabel: 'Graph (nodes;from,to,weight;...)', defaultInput: '5;0,1,6;0,2,7;1,2,8;1,3,5;1,4,-4;2,3,-3;2,4,9;3,1,-2;4,3,7', needsTarget: true, targetLabel: 'Start node', defaultTarget: 0, description: 'Like Dijkstra, Bellman-Ford finds the shortest path from a starting point to every other location. The difference is that some roads have negative costs — maybe a road gives you fuel instead of consuming it. Dijkstra can\'t handle this, but Bellman-Ford can. It works by going through every single road in the graph repeatedly — once for each node — and asking: can I find a cheaper way to reach this destination? It also detects a dangerous trap called a negative cycle, where a loop of roads keeps reducing your cost forever, making a true shortest path impossible.' },
  { name: 'Topological Sort', slug: 'topological-sort', endpoint: 'topological-sort', category: 'graph', inputType: 'graph', inputLabel: 'DAG (nodes;from,to;...)', defaultInput: '6;5,2;5,0;4,0;4,1;2,3;3,1', description: 'Imagine a list of university courses where some courses require you to take others first — you can\'t take Algorithms before taking Data Structures. Topological Sort arranges all the courses in a valid order so that every prerequisite always appears before the course that needs it. It only works on graphs with no circular dependencies — you can\'t have course A require course B which requires course A. The result is a flat ordered list where every arrow in the original graph always points forward, never backward.' },
  { name: 'Cycle Detection', slug: 'cycle-detection', endpoint: 'cycle-detection', category: 'graph', inputType: 'graph', inputLabel: 'Graph (nodes;from,to;...)', defaultInput: '4;0,1;1,2;2,3;3,1', description: 'Imagine you\'re following a trail of arrows between cities and you want to know if any trail loops back on itself — if you could end up going in circles forever. Cycle Detection walks the graph using DFS and color-codes every city as it goes: white means unvisited, grey means currently being explored, black means fully done. If you ever follow an arrow and land on a grey city — one you\'re already in the middle of exploring — you\'ve found a cycle. A black city is safe, only grey means trouble.' },
  { name: 'Union-Find', slug: 'union-find', endpoint: 'union-find', category: 'graph', inputType: 'graph', inputLabel: 'Graph (nodes;from,to;...)', defaultInput: '5;0,1;1,2;3,4', description: 'Imagine a group of people at a party and you want to track who is connected to whom — directly or through mutual friends. Union-Find maintains a collection of groups. It supports two actions: Find — which group does this person belong to? And Union — merge the groups of these two people together. Internally, each group is represented like a tree, and every person points toward the root of their group. Checking if two people are connected is as simple as checking if they share the same root.' },
  { name: "Kruskal's MST", slug: 'kruskal', endpoint: 'kruskal', category: 'graph', inputType: 'graph', inputLabel: 'Graph (nodes;from,to,weight;...)', defaultInput: '4;0,1,10;0,2,6;0,3,5;1,3,15;2,3,4', description: 'Imagine you\'re building a road network to connect a group of cities as cheaply as possible — every city must be reachable but you want to spend the least on road construction. Kruskal\'s algorithm sorts all possible roads by cost, cheapest first, and goes through them one by one. It adds a road to the network only if it connects two cities that aren\'t already connected — skipping any road that would create a redundant loop. It keeps adding roads until every city is connected. The result is a Minimum Spanning Tree — the cheapest possible network that reaches everywhere.' },
  { name: "Prim's MST", slug: 'prim', endpoint: 'prim', category: 'graph', inputType: 'graph', inputLabel: 'Graph (nodes;from,to,weight;...)', defaultInput: '4;0,1,10;0,2,6;0,3,5;1,3,15;2,3,4', needsTarget: true, targetLabel: 'Start node', defaultTarget: 0, description: 'Prim\'s algorithm solves the exact same problem as Kruskal\'s — building the cheapest road network to connect all cities — but it grows the network differently. Instead of sorting all roads upfront, it starts at one city and at each step looks at all roads leading out of the already-connected network. It always picks the cheapest one that reaches a new city not yet in the network, adds that city, and repeats. It grows outward like a spreading tree, one cheapest branch at a time, until every city is connected.' },
];

export const dpConfig: AlgorithmConfig[] = [
  { name: 'Fibonacci', slug: 'fibonacci', endpoint: 'fibonacci', category: 'dp', inputType: 'number', inputLabel: 'n', defaultInput: '10', description: 'Imagine you\'re counting how many rabbits you have each month, where every month each pair of adult rabbits produces a new pair. The sequence goes 1, 1, 2, 3, 5, 8, 13... — each number is just the sum of the two before it. Simple enough, but if you calculate it naively, you end up solving the same smaller problems over and over. Dynamic programming fixes this by writing down every answer as you go — a technique called memoization. The moment you\'ve calculated a number, you remember it, so if you ever need it again you just look it up instead of recalculating it from scratch.' },
  { name: '0/1 Knapsack', slug: 'knapsack', endpoint: 'knapsack', category: 'dp', inputLabel: 'Weights', defaultInput: '1,3,4,5', needsTarget: true, targetLabel: 'Capacity', defaultTarget: 7, needsPattern: true, patternLabel: 'Values', defaultPattern: '1,4,5,7', description: 'Imagine you\'re a hiker packing a bag that can hold a maximum weight of 7kg. You have several items, each with a weight and a value. You want to pack the most valuable combination without exceeding the weight limit — and each item is either fully packed or left behind, no splitting allowed. The algorithm builds a grid where each row represents adding one more item to consider, and each column represents a different weight capacity. Each cell answers: what\'s the best value I can pack given these items and this capacity? It fills the grid step by step, each cell borrowing the best answer from above.' },
  { name: 'Longest Common Subsequence', slug: 'lcs', endpoint: 'lcs', category: 'dp', inputType: 'text', inputLabel: 'Text 1', defaultInput: 'ABCBDAB', needsPattern: true, patternLabel: 'Text 2', defaultPattern: 'BDCAB', description: 'Imagine two words — "ABCBDAB" and "BDCAB" — and you want to find the longest sequence of letters that appears in both, in the same order, but not necessarily side by side. For example "BCAB" appears in both if you skip around. LCS builds a grid comparing every letter of one word against every letter of the other. When two letters match, it extends the best subsequence found so far. When they don\'t, it borrows the best answer from either ignoring the current letter of word one or word two — whichever is longer.' },
  { name: 'Longest Increasing Subsequence', slug: 'lis', endpoint: 'lis', category: 'dp', inputLabel: 'Array', defaultInput: '10,22,9,33,21,50,41,60', description: 'Imagine a row of numbers: 10, 22, 9, 33, 21, 50, 41, 60. You want to find the longest chain of numbers that are strictly going up — but they don\'t have to be next to each other, you can skip numbers as long as the ones you pick keep climbing. For example 10, 22, 33, 50, 60 is one valid chain. The algorithm goes through each number and asks: what\'s the longest increasing chain that ends at this number? It looks back at all previous numbers smaller than the current one and builds on the best chain among them.' },
  { name: 'Coin Change', slug: 'coin-change', endpoint: 'coin-change', category: 'dp', inputLabel: 'Coins', defaultInput: '1,5,10,25', needsTarget: true, targetLabel: 'Amount', defaultTarget: 30, description: 'Imagine you want to make exactly 30 cents using coins of 1, 5, 10, and 25 cents, using as few coins as possible. Instead of trying every combination, the algorithm builds up from zero. It asks: what\'s the fewest coins needed to make 1 cent? 2 cents? 3 cents? All the way up to 30. For each amount, it tries every coin and asks: if I use this coin, what\'s the fewest coins needed for the remaining amount? It picks whichever coin leaves the smallest total, building the answer step by step from the ground up.' },
  { name: 'Edit Distance', slug: 'edit-distance', endpoint: 'edit-distance', category: 'dp', inputType: 'text', inputLabel: 'Text 1', defaultInput: 'kitten', needsPattern: true, patternLabel: 'Text 2', defaultPattern: 'sitting', description: 'This is the same idea as Levenshtein Distance — finding the minimum number of insertions, deletions, or replacements needed to turn one word into another. The difference here is the emphasis on how dynamic programming makes it efficient. Instead of guessing, it builds a grid comparing every prefix of one word against every prefix of the other. Each cell asks: what\'s the cheapest way to match these two prefixes? It looks at its three neighbors — the cell above, to the left, and diagonally — representing delete, insert, and replace, and always picks the cheapest option.' },
  { name: 'Subset Sum', slug: 'subset-sum', endpoint: 'subset-sum', category: 'dp', inputLabel: 'Set', defaultInput: '3,34,4,12,5,2', needsTarget: true, targetLabel: 'Target', defaultTarget: 9, description: 'Imagine you have a bag of numbered stones — 3, 34, 4, 12, 5, 2 — and you want to know if any combination of them adds up to exactly 9. You don\'t need to find the combination, just whether it\'s possible. The algorithm builds a grid where each row adds one more stone to consider, and each column represents a target sum from 0 up to 9. Each cell answers: is it possible to reach this sum using only the stones considered so far? It fills the grid by checking: can I reach this sum without the current stone, or can I reach what\'s left after using it?' },
  { name: 'Climbing Stairs', slug: 'climbing-stairs', endpoint: 'climbing-stairs', category: 'dp', inputType: 'number', inputLabel: 'Stairs (n)', defaultInput: '8', description: 'Imagine a staircase with 8 steps. You can take either 1 step or 2 steps at a time. How many different ways can you reach the top? It turns out the answer follows the same pattern as Fibonacci. To reach step 8, you either came from step 7 (took 1 step) or from step 6 (took 2 steps). So the number of ways to reach step 8 is just the number of ways to reach step 7 plus the number of ways to reach step 6. The algorithm builds this up from the bottom — starting from step 1 and step 2 — remembering each answer until it reaches the top.' },
];

export const backtrackingConfig: AlgorithmConfig[] = [
  { name: 'N-Queens', slug: 'n-queens', endpoint: 'n-queens', category: 'backtracking', inputType: 'number', inputLabel: 'Board size (n)', defaultInput: '4', description: 'Imagine placing 4 queens on a 4×4 chessboard so that no queen can attack another — no two queens can share the same row, column, or diagonal. The algorithm places one queen at a time, row by row. For each row it tries every column, and before placing a queen it checks: is this square safe from all queens already placed? If yes, it places it and moves to the next row. If it gets stuck — no safe square exists in the current row — it backtracks to the previous row, moves that queen to the next available safe square, and tries again. It keeps placing and backtracking until all queens are safely placed.' },
  { name: 'Sudoku Solver', slug: 'sudoku', endpoint: 'sudoku', category: 'backtracking', inputLabel: 'Grid (81 values, 0=empty)', defaultInput: '5,3,0,0,7,0,0,0,0,6,0,0,1,9,5,0,0,0,0,9,8,0,0,0,0,6,0,8,0,0,0,6,0,0,0,3,4,0,0,8,0,3,0,0,1,7,0,0,0,2,0,0,0,6,0,6,0,0,0,0,2,8,0,0,0,0,4,1,9,0,0,5,0,0,0,0,8,0,0,7,9', description: 'Imagine a 9×9 Sudoku grid with some numbers already filled in. The rule is every row, column, and 3×3 box must contain the digits 1 through 9 with no repeats. The algorithm scans for the first empty cell and tries placing every digit from 1 to 9. For each digit it asks: does this break any rule? If not, it fills the cell and moves to the next empty one. If it ever reaches a cell where no digit fits, it backtracks — erases the last placed digit, tries the next one, and continues. It keeps filling and backtracking until every cell is filled correctly.' },
  { name: 'Generate Permutations', slug: 'permutations', endpoint: 'permutations', category: 'backtracking', inputLabel: 'Array', defaultInput: '1,2,3', description: 'Imagine you have three numbered tiles — 1, 2, 3 — and you want to list every possible order they can be arranged in. The algorithm builds each arrangement one position at a time. It picks a tile for the first position, then picks from the remaining tiles for the second position, then the last tile fills the third. Every time it completes a full arrangement, it records it, then backtracks and swaps in a different tile to explore the next arrangement. It keeps doing this until every possible ordering has been found.' },
  { name: 'Generate Subsets', slug: 'subsets', endpoint: 'subsets', category: 'backtracking', inputLabel: 'Array', defaultInput: '1,2,3', description: 'Imagine the same three tiles — 1, 2, 3 — and you want every possible group you can form from them, including the empty group and the full group. That\'s 8 subsets in total. For each tile, the algorithm makes a simple yes or no decision: include it or leave it out. It builds subsets like a branching tree of decisions — at each step it branches into two paths, one with the current tile and one without. Every time it reaches the end of the tile list, it records whatever combination it has built so far.' },
  { name: 'Rat in a Maze', slug: 'rat-in-maze', endpoint: 'rat-in-maze', category: 'backtracking', inputLabel: 'Grid (1=open, 0=blocked)', defaultInput: '1,0,0,0,1,1,0,0,0,1,1,0,0,0,0,1', needsTarget: true, targetLabel: 'Grid size (n)', defaultTarget: 4, description: 'Imagine a rat sitting in the top-left corner of a grid. Some cells are open and some are blocked. The rat wants to reach the bottom-right corner. The algorithm tries moving right first, then down. Before each move it checks: is this cell open and not yet visited? If yes, it steps in and tries again from there. If it gets completely stuck with no valid moves, it backtracks — steps back to the previous cell and tries a different direction. It keeps exploring and backtracking until it finds a path to the exit or confirms no path exists.' },
  { name: 'Word Search in Grid', slug: 'word-search', endpoint: 'word-search', category: 'backtracking', inputType: 'text', inputLabel: 'Grid (rows separated by ;)', defaultInput: 'ABCE;SFCS;ADEE', needsPattern: true, patternLabel: 'Word', defaultPattern: 'ABCCED', description: 'Imagine a grid of random letters and you\'re looking for the word "ABCCED" hidden somewhere in it, where each next letter must be directly above, below, left, or right of the previous one. The algorithm scans every cell in the grid looking for the first letter of the word. When it finds one, it tries to extend the match in all four directions, letter by letter. If it ever hits a wrong letter or a dead end, it backtracks — unmarks the path and tries a different direction. It keeps searching until it either spells out the full word or exhausts every possibility.' },
  { name: 'Combination Sum', slug: 'combination-sum', endpoint: 'combination-sum', category: 'backtracking', inputLabel: 'Candidates', defaultInput: '2,3,6,7', needsTarget: true, targetLabel: 'Target', defaultTarget: 7, description: 'Imagine you have the numbers 2, 3, 6, and 7, and you want to find every combination that adds up to exactly 7 — you can reuse numbers as many times as you want. The algorithm builds combinations one number at a time, keeping a running total. Each time it adds a number it checks: did I hit the target? If yes, record the combination. Did I go over? Backtrack and try the next candidate. It explores every possible combination by diving deep into one path, then stepping back and branching into the next, until all valid combinations are found.' },
  { name: 'Palindrome Partitioning', slug: 'palindrome-partitioning', endpoint: 'palindrome-partitioning', category: 'backtracking', inputType: 'text', inputLabel: 'Text', defaultInput: 'aab', description: 'Imagine the word "aab" and you want to find every way to split it into parts where each part reads the same forwards and backwards. For example "a", "a", "b" works because each piece is a single letter — and single letters are always palindromes. The algorithm tries every possible cut point from left to right. At each step it asks: is the current piece a palindrome? If yes, it records it and keeps cutting the remaining string. If no valid cut exists, it backtracks and tries a different split point, until every valid partitioning has been found.' },
];

export const nrTheoryConfig: AlgorithmConfig[] = [
  { name: 'Sieve of Eratosthenes', slug: 'sieve', endpoint: 'sieve', category: 'number-theory', inputType: 'number', inputLabel: 'Upper bound (n)', defaultInput: '30', description: 'Imagine you have a list of every number from 2 to 30 and you want to cross out all the non-primes, leaving only the primes behind. Start at 2 — the first prime. Cross out every multiple of 2: 4, 6, 8, and so on. Move to the next uncrossed number — 3. Cross out every multiple of 3. Keep going: the next uncrossed number is always a prime, and you cross out all its multiples. By the time you reach the end of the list, every number still standing is a prime. You never had to test any of them individually — you just kept eliminating their multiples.' },
  { name: 'Euclidean Algorithm (GCD)', slug: 'gcd', endpoint: 'gcd', category: 'number-theory', inputType: 'numbers', inputLabel: 'a, b', defaultInput: '48,18', description: 'Imagine you have two pieces of rope — one 48cm and one 18cm — and you want to find the longest ruler that measures both perfectly with no leftover. The Euclidean algorithm works like this: divide the longer rope by the shorter one and keep only the remainder. Now repeat with the shorter rope and the remainder. Keep going until the remainder is zero — the last non-zero remainder is your answer. For 48 and 18: 48 ÷ 18 leaves 12, then 18 ÷ 12 leaves 6, then 12 ÷ 6 leaves 0. The answer is 6 — the greatest common divisor.' },
  { name: 'Prime Factorization', slug: 'prime-factorization', endpoint: 'prime-factorization', category: 'number-theory', inputType: 'number', inputLabel: 'n', defaultInput: '84', description: 'Imagine breaking a number like 84 apart into the smallest possible building blocks — numbers that can\'t be divided any further. These building blocks are called prime numbers. The algorithm starts by trying to divide 84 by the smallest prime, 2. It divides as many times as it can: 84 ÷ 2 = 42, 42 ÷ 2 = 21. Now 21 isn\'t divisible by 2, so it tries 3: 21 ÷ 3 = 7. And 7 is itself a prime, so it stops. The result is 2 × 2 × 3 × 7 — the unique set of prime building blocks that multiply together to make 84.' },
  { name: 'Bit Manipulation', slug: 'bit-manipulation', endpoint: 'bit-manipulation', category: 'number-theory', inputType: 'number', inputLabel: 'n', defaultInput: '42', description: 'Every number in a computer is stored as a sequence of 1s and 0s — called bits. For example, the number 42 is stored as 101010 in binary. Bit manipulation is a set of tricks that work directly on these 1s and 0s instead of the number as a whole, making certain operations extremely fast. AND keeps a bit only if both numbers have a 1 there. OR keeps a bit if either number has a 1 there. XOR keeps a bit only if exactly one of the two numbers has a 1 there. These simple rules unlock surprisingly powerful shortcuts — like checking if a number is even, counting how many 1s it has, or swapping two values without using a third variable.' },
];

export const allConfigs: Record<string, AlgorithmConfig[]> = {
  array: arrayConfig,
  string: stringConfig,
  tree: treeConfig,
  graph: graphConfig,
  dp: dpConfig,
  backtracking: backtrackingConfig,
  'number-theory': nrTheoryConfig,
};
